### Exercici 1

- Descarrega el data set Airlines Delay: Airline on-time statistics and delay causes i carrega’l a un Pandas Dataframe. Explora les dades que conté, explica breument quines variables hi ha i queda’t únicament amb les columnes que consideris rellevants. Justifica la teva elecció.

- Redueix la dimensió del dataset de manera aleatòria per tal d'obtenir un dataset de només 200.000 registres. Tots els exercicis s'han de fer amb aquest dataset reduït.

- https://www.kaggle.com/datasets/giovamata/airlinedelaycauses

In [55]:
import pandas as pd

df = pd.read_csv("DelayedFlights.csv")

In [56]:
# Verifico el tamany del data set

print(len(df))

1936758

In [57]:
# Modifico les opcions de visualització per tal de veure totes les columnes i un determinat nombre de files

pd.options.display.max_columns = None
pd.options.display.max_rows = 100

# Mostrar els valor float amb només quatre decimals

pd.set_option('display.float_format', '{:.4f}'.format)

In [58]:
# Trec els primers 5 registres per veure com estan representades les dades

df.head(10)

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,TailNum,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,DepDelay,Origin,Dest,Distance,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,0,2008,1,3,4,2003.0000,1955,2211.0000,2225,WN,335,N712SW,128.0000,150.0000,116.0000,-14.0000,8.0000,IAD,TPA,810,4.0000,8.0000,0,N,0,NaN,NaN,NaN,NaN,NaN
1,1,2008,1,3,4,754.0000,735,1002.0000,1000,WN,3231,N772SW,128.0000,145.0000,113.0000,2.0000,19.0000,IAD,TPA,810,5.0000,10.0000,0,N,0,NaN,NaN,NaN,NaN,NaN
2,2,2008,1,3,4,628.0000,620,804.0000,750,WN,448,N428WN,96.0000,90.0000,76.0000,14.0000,8.0000,IND,BWI,515,3.0000,17.0000,0,N,0,NaN,NaN,NaN,NaN,NaN
3,4,2008,1,3,4,1829.0000,1755,1959.0000,1925,WN,3920,N464WN,90.0000,90.0000,77.0000,34.0000,34.0000,IND,BWI,515,3.0000,10.0000,0,N,0,2.0000,0.0000,0.0000,0.0000,32.0000
4,5,2008,1,3,4,1940.0000,1915,2121.0000,2110,WN,378,N726SW,101.0000,115.0000,87.0000,11.0000,25.0000,IND,JAX,688,4.0000,10.0000,0,N,0,NaN,NaN,NaN,NaN,NaN
5,6,2008,1,3,4,1937.0000,1830,2037.0000,1940,WN,509,N763SW,240.0000,250.0000,230.0000,57.0000,67.0000,IND,LAS,1591,3.0000,7.0000,0,N,0,10.0000,0.0000,0.0000,0.0000,47.0000
6,10,2008,1,3,4,706.0000,700,916.0000,915,WN,100,N690SW,130.0000,135.0000,106.0000,1.0000,6.0000,IND,MCO,828,5.0000,19.0000,0,N,0,NaN,NaN,NaN,NaN,NaN
7,11,2008,1,3,4,1644.0000,1510,1845.0000,1725,WN,1333,N334SW,121.0000,135.0000,107.0000,80.0000,94.0000,IND,MCO,828,6.0000,8.0000,0,N,0,8.0000,0.0000,0.0000,0.0000,72.0000
8,15,2008,1,3,4,1029.0000,1020,1021.0000,1010,WN,2272,N263WN,52.0000,50.0000,37.0000,11.0000,9.0000,IND,MDW,162,6.0000,9.0000,0,N,0,NaN,NaN,NaN,NaN,NaN
9,16,2008,1,3,4,1452.0000,1425,1640.0000,1625,WN,675,N286WN,228.0000,240.0000,213.0000,15.0000,27.0000,IND,PHX,1489,7.0000,8.0000,0,N,0,3.0000,0.0000,0.0000,0.0000,12.0000

In [59]:
# Verifico el tipus de dades

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1936758 entries, 0 to 1936757
Data columns (total 30 columns):
 #   Column             Dtype
---  ------             -----
 0   Unnamed: 0         int64
 1   Year               int64
 2   Month              int64
 3   DayofMonth         int64
 4   DayOfWeek          int64
 5   DepTime            float64
 6   CRSDepTime         int64
 7   ArrTime            float64
 8   CRSArrTime         int64
 9   UniqueCarrier      object
 10  FlightNum          int64
 11  TailNum            object
 12  ActualElapsedTime  float64
 13  CRSElapsedTime     float64
 14  AirTime            float64
 15  ArrDelay           float64
 16  DepDelay           float64
 17  Origin             object
 18  Dest               object
 19  Distance           int64
 20  TaxiIn             float64
 21  TaxiOut            float64
 22  Cancelled          int64
 23  CancellationCode   object
 24  Diverted           int64
 25  CarrierDelay       float64
 26  WeatherDelay       float64
 27  NASDelay           float64
 28  SecurityDelay      float64
 29  LateAircraftDelay  float64
dtypes: float64(14), int64(11), object(5)
memory usage: 443.3+ MB

In [60]:
# Abans d'esborrar les dades he volgut veure quins valors únics hi ha per cada categoria (columna)

for column in df.columns:
    unique_count = df[column].nunique()
    unique_values = df[column].unique()
    print(f"Column '{column}' has {unique_count} unique values:")
    print(unique_values)

Column 'Unnamed: 0' has 1936758 unique values:
[      0       1       2 ... 7009718 7009726 7009727]
Column 'Year' has 1 unique values:
[2008]
Column 'Month' has 12 unique values:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Column 'DayofMonth' has 31 unique values:
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
 27 28 29 30 31  2  1]
Column 'DayOfWeek' has 7 unique values:
[4 5 6 7 1 2 3]
Column 'DepTime' has 1438 unique values:
[2003.  754.  628. ...  502.  503.  425.]
Column 'CRSDepTime' has 1207 unique values:
[1955  735  620 ... 2331   48  140]
Column 'ArrTime' has 1440 unique values:
[2211. 1002.  804. ...  401.  437.  405.]
Column 'CRSArrTime' has 1364 unique values:
[2225 1000  750 ...  305  334  147]
Column 'UniqueCarrier' has 20 unique values:
['WN' 'XE' 'YV' 'OH' 'OO' 'UA' 'US' 'DL' 'EV' 'F9' 'FL' 'HA' 'MQ' 'NW'
 '9E' 'AA' 'AQ' 'AS' 'B6' 'CO']
Column 'FlightNum' has 7499 unique values:
[ 335 3231  448 ... 6869 6870 5272]
Column 'TailNum' has 5366 unique values:
['N712SW' 'N772SW' 'N428WN' ... 'N75428' 'N75429' 'N78008']
Column 'ActualElapsedTime' has 673 unique values:
[ 128.   96.   90.  101.  240.  130.  121.   52.  228.  226.  123.   56.
   57.   54.   59.  155.  165.  147.  154.  146.  145.  135.  127.  153.
  150.  152.  163.  136.   69.   70.  143.   71.   99.   86.   65.   63.
  119.  134.   51.   75.   74.   83.   79.  256.  124.  148.  149.  275.
  196.  204.   98.  233.   66.   58.   64.   60.   73.  260.  245.  242.
  212.  235.  110.  109.   92.   91.  159.  174.  158.  252.  194.  208.
  295.   61.   68.   72.   82.  114.  164.  117.  175.  156.  157.  254.
  197.  219.  200.  186.  192.  187.  185.  193.  270.  182.   94.  100.
  113.   95.  144.  137.   46.   50.   47.  251.  126.  141.  129.  269.
  261.   80.   62.   55.  229.  244.  293.  237.   84.   76.   67.  140.
  133.  162.  103.  118.   88.   85.   87.   89.   81.  178.  171.  169.
  232.   97.  160.  215.  105.   53.  168.  209.  210.  277.  111.   78.
   77.   93.  132.  201.  115.  139.  125.  142.  102.  179.  227.  217.
  220.  151.  241.  180.  167.  206.  223.   49.   48.  161.  170.  122.
  106.  312.  176.  172.  177.  166.  104.  298.   44.  116.   41.  239.
  267.  231.  225.  230.  236.  234.  265.  276.  262.  120.  138.  286.
  287.  294.  300.  107.  221.  238.  224.  255.  268.  253.  296.  281.
  203.  334.  338.  131.  250.  190.  183.  173.  324.  222.  202.  205.
  319.  310.  189.  243.  191.  181.  188.  184.  284.  108.  112.  266.
  332.  337.  278.  216.   40.  282.  207.   nan   45.  195.   39.  299.
  274.   42.   38.  341.   43.  289.  308.  198.  320.  290.  301.  303.
  331.  350.  214.  199.  279.  246.  271.  259.  305.  213.  218.  288.
  273.  283.  272.  292.  264.  249.  318.  248.  247.  344.  339.  309.
  211.  342.  297.  316.  353.  336.  317.  367.  263.  285.  307.  311.
  372.  328.  315.  351.  321.  330.  314.  313.  357.  352.  291.  258.
  257.  304.  349.  302.  348.  340.  347.  343.  323.  280.  345.  326.
   37.  329.  327.  306.   36.  333.  360.  325.  322.  335.  355.  365.
   35.  368.   25.  374.  356.  346.  354.   33.   29.   32.   34.   30.
   28.   27.   31.  433.   26.   24.  388.  551.  538.  527.  571.  556.
  552.  523.  512.  540.  541.  495.  450.  447.  463.  476.  465.  478.
  454.  468.  457.  532.  528.  557.  566.  558.  536.  509.  517.  401.
  386.  375.  418.  481.  373.  376.  420.  405.  397.  381.  362.  366.
  384.  382.  378.  369.  408.  442.  436.  399.  435.  391.  394.  363.
  431.  425.  396.  419.  403.  412.  400.  387.  407.  423.  414.  424.
  379.  389.  430.  371.  390.  404.  402.  416.  385.  392.  370.  380.
  361.  434.  441.  445.  426.  448.  413.  452.  515.  411.  359.  449.
  364.  398.  377.  409.  395.  393.  421.  358.  422.  432.  415.  383.
  438.  406.  472.  440.  427.  444.  417.  410.  466.  437.  547.  594.
  619.  663.  514.  598.  616.  513.  601.  693.  584.  475.  606.  488.
  453.  623.  605.  489.  615.  499.  455.  486.  439.  459.  508.  526.
  497.  485.  502.  550.  504.  511.  490.  531.  429.  428.  491.  507.
  506.  562.  561.  564.  579.  543.  569.  559.  546.  539.  576.  583.
  482.  498.  461.  451.  443.   22.   21.   19.   23.   20.  479.  462.
  505.  567.  634.  473.  658.  646.  501.  645.  667.  635.  614.  467.
  661.  446.  624.  629.  621.  640.  484.  649.  664.  494.  537.  456.
  626.  480.  460.  609.  570.  662.  520.  611.  596.  589.  572.  588.
  607.  617.  521.  633.  487.  592.  612.   17.  533.  554.  524.  519.
  593.  471.  679.  500.  470.  510.  464.  565.  620.  595.  483.  627.
  648.  493.  631.  585.  587.  586.  549.  516.  535.  492.  542.  503.
  477.  563.  574.  560.  496.  534.   18.   15.  474.  653.  637.  630.
  697.  625.  670.  628.  666.  698.  651.  659.  469.  647.  657.  568.
  582.  613.  610.  525.  555.  529.  581.  458.  530.  578.  602.  604.
  522.  553.  727.  548.  580.   16.  577.  644.  642.  660.  682.  636.
  687.  686.  672.  711.  683.  518.  575.  599.  544.  573.  641.  669.
  597.  638.  591.  608.  600.  545.  622.  632.  681.  590.  618.  654.
  643.  639.  675.  776.  724.  650.  656.  750.   14.  603. 1114.  652.
  702.  790.]
Column 'CRSElapsedTime' has 515 unique values:
[150. 145.  90. 115. 250. 135.  50. 240.  70. 195. 190. 165. 170. 180.
 185. 130.  80. 100.  75.  95. 125.  55.  85. 275. 120. 160. 155. 285.
 210. 205. 110.  60.  65. 265. 260. 230. 175. 215. 200. 290. 140. 270.
 245. 105. 225. 235. 220. 255. 315. 300.  45. 280. 365. 355. 335. 345.
 340. 295. 370. 305. 310. 360. 330. 320. 350. 325.  71. 198.  84. 173.
  67. 134. 128. 108. 132. 174. 201. 182.  57. 103. 141. 129. 123.  58.
 101. 126. 214. 122. 149.  77.  63. 231.  20.  69.  79. 117.  73. 153.
 197. 162. 112.  62. 124. 137. 159. 243. 194.  86. 239. 193.  17. 184.
 144. 151. 127.  81. 104. 158. 139. 131.  19. 192. 181. 167. 209. 213.
  56. 163. 223. 154. 148. 111.  92. 161. 183. 188. 206. 142.  68. 107.
 106. 102. 147. 171. 156. 204. 146. 113. 118.  78. 168.  88.  82. 157.
 152.  89. 178. 172.  74. 187.  97.  87. 109.  83. 218. 169. 207.  94.
 133.  72.  64. 143. 189. 119. 164. 227.  93.  99.  98. 202. 114. 179.
 138.  59. 208. 136.  66.  53. 211.  43. 177.  54. 196.  52. 219.  49.
 199. 186.  47.  46.  76.  96. 203.  44. 121.  34.  48. 166.  91.  38.
 176.  61. 224. 116.  40.  39.  35.  51.  32. 191. 216.  42. 313.  41.
  36.  25. 217. 262.  37.  31.  26. 234. 246. 257.  30. 237. 244. 226.
  23.  33. 552. 556. 476. 474. 470. 471. 547. 548. 333. 324. 392. 396.
 338. 407. 404. 389. 394. 323. 321. 409. 395. 312. 386. 372. 383. 381.
 307. 406. 393. 248. 319. 329. 282. 277. 362. 328. 344. 348. 439. 465.
 279. 283. 343. 347. 299. 342. 314. 298. 296. 317. 375. 336. 316. 352.
 302. 301. 274. 366. 397. 441. 303. 331. 297. 294. 341. 351. 363. 308.
 361. 334. 332. 388. 390. 379. 382. 254. 268. 271. 251. 267. 269. 252.
 273. 266. 276. 287. 281. 242. 241. 288. 233. 238. 322. 326. 385. 318.
 403. 400. 380. 356. 391. 309. 371. 304. 286. 293. 359. 339. 284. 292.
 232. 354. 367. 236. 291. 289. 264. 258. 272. 263. 221. 249. 228. 253.
 229. 212. 261. 222. 337. 247. 377. 327. 475. 405. 357. 401. 399. 449.
 456. 259. 278. 349. 311. 306. 374. 413. 378. 423. 426. 402. 358. 384.
 256. 412. 353. 373. 369. 364. 346. 368. 420. 398. 421. 387. 524. 597.
 600. 512. 416. 425. 419. 455. 440.  29.   1. 461. 513. 523.  nan 510.
 415. 500. 435. 560.  28.  27. 417. 505. 376. 660. 450. 565. 418. 427.
 408. 414.  18.  -9.  16. 515. 458. 430. 490. 460. 410. -21.  24. 541.
 444. 601. 595. 525.  21. 585. 535. 575. 635. 602.  15. -25. -12. 481.
 533. 443. 584. 528. 511. 495. 549. 445.   8. 526. 448. 446. 463. -10.
 -18.  12. 531. 478. 472. 436. 452. 422. 577. 573. 529. 485. 480. 540.
  14. 437. 432.   9. 453. 462. 536. 605. 473. 514. 532. 477. 438. 468.
 579. 527. 520. 479. 442. 587. 522. 580. 411.   2. 542. 604.]
Column 'AirTime' has 650 unique values:
[1.160e+02 1.130e+02 7.600e+01 7.700e+01 8.700e+01 2.300e+02 1.060e+02
 1.070e+02 3.700e+01 2.130e+02 2.050e+02 1.100e+02 4.900e+01 4.700e+01
 5.000e+01 1.430e+02 1.550e+02 1.340e+02 1.400e+02 1.180e+02 1.140e+02
 1.380e+02 1.510e+02 1.440e+02 1.210e+02 5.900e+01 6.000e+01 8.100e+01
 9.700e+01 7.200e+01 5.400e+01 1.250e+02 1.040e+02 1.200e+02 3.900e+01
 3.600e+01 3.800e+01 6.500e+01 2.430e+02 9.100e+01 1.310e+02 1.270e+02
 1.350e+02 2.530e+02 1.780e+02 1.830e+02 1.770e+02 7.300e+01 2.210e+02
 4.600e+01 4.800e+01 4.300e+01 2.440e+02 1.950e+02 2.010e+02 7.900e+01
 8.800e+01 7.800e+01 8.500e+01 8.000e+01 1.470e+02 1.460e+02 1.500e+02
 2.320e+02 1.760e+02 1.790e+02 2.690e+02 4.200e+01 4.000e+01 4.100e+01
 4.500e+01 4.400e+01 9.000e+01 1.480e+02 9.500e+01 1.390e+02 1.300e+02
 1.360e+02 2.340e+02 1.750e+02 1.810e+02 1.690e+02 1.710e+02 1.680e+02
 2.570e+02 1.660e+02 7.400e+01 7.100e+01 1.320e+02 3.400e+01 3.200e+01
 2.370e+02 1.120e+02 2.450e+02 2.100e+02 2.180e+02 2.660e+02 2.310e+02
 2.220e+02 5.700e+01 5.500e+01 6.100e+01 5.600e+01 5.100e+01 1.260e+02
 1.220e+02 1.920e+02 1.290e+02 1.190e+02 7.500e+01 9.800e+01 7.000e+01
 6.900e+01 6.800e+01 6.600e+01 5.800e+01 6.200e+01 6.700e+01 6.400e+01
 1.570e+02 2.170e+02 5.300e+01 8.200e+01 2.030e+02 2.000e+02 8.600e+01
 1.590e+02 1.540e+02 1.560e+02 2.020e+02 6.300e+01 5.200e+01 1.410e+02
 8.400e+01 1.880e+02 1.230e+02 1.020e+02 8.300e+01 1.640e+02 1.620e+02
 1.960e+02 2.280e+02 2.140e+02 1.600e+02 1.870e+02 2.080e+02 1.490e+02
 9.600e+01 9.400e+01 1.330e+02 1.170e+02 1.090e+02 1.110e+02 1.150e+02
 2.250e+02 1.370e+02 2.910e+02 1.520e+02 1.530e+02 9.200e+01 1.240e+02
 1.280e+02 2.760e+02 3.500e+01 3.000e+01 3.100e+01 3.300e+01 1.610e+02
 1.050e+02 1.580e+02 1.000e+02 1.420e+02 2.700e+01 2.190e+02 2.150e+02
 2.160e+02 2.200e+02 2.230e+02 2.490e+02 2.560e+02 2.520e+02 2.590e+02
 2.650e+02 2.720e+02 2.470e+02 9.300e+01 2.070e+02 2.120e+02 2.090e+02
 1.080e+02 2.380e+02 2.580e+02 2.420e+02 2.740e+02 2.680e+02 2.670e+02
 2.600e+02 1.860e+02 1.850e+02 3.200e+02 1.930e+02 1.890e+02 1.700e+02
 2.040e+02 8.900e+01 1.450e+02 1.970e+02 3.080e+02 1.010e+02 3.050e+02
 1.030e+02 2.940e+02 2.790e+02 1.630e+02 1.650e+02 2.330e+02 1.940e+02
 1.720e+02 1.730e+02 9.900e+01 2.360e+02 2.350e+02 2.510e+02 3.180e+02
 3.240e+02 2.800e+01 1.910e+02 1.990e+02       nan 1.740e+02 2.900e+01
 1.800e+02 2.270e+02 2.060e+02 1.820e+02 2.860e+02 1.670e+02 3.250e+02
 2.710e+02 2.110e+02 2.870e+02 2.240e+02 2.980e+02 2.850e+02 2.920e+02
 3.310e+02 2.880e+02 2.540e+02 3.270e+02 2.500e+02 2.400e+02 1.980e+02
 2.770e+02 2.480e+02 2.610e+02 2.550e+02 2.640e+02 2.750e+02 2.800e+02
 2.780e+02 2.700e+02 2.620e+02 3.170e+02 3.030e+02 1.900e+02 3.290e+02
 2.630e+02 3.110e+02 3.100e+02 2.950e+02 3.510e+02 2.260e+02 2.290e+02
 2.460e+02 2.390e+02 2.810e+02 2.830e+02 3.440e+02 3.260e+02 3.150e+02
 2.930e+02 2.890e+02 3.360e+02 3.040e+02 2.970e+02 3.430e+02 3.410e+02
 2.410e+02 2.600e+01 3.160e+02 3.140e+02 2.820e+02 3.380e+02 2.500e+01
 1.840e+02 2.900e+02 3.300e+02 3.020e+02 3.340e+02 3.320e+02 3.280e+02
 3.130e+02 3.060e+02 3.120e+02 3.220e+02 2.840e+02 2.990e+02 2.730e+02
 3.000e+02 3.070e+02 3.210e+02 3.090e+02 3.190e+02 2.960e+02 3.350e+02
 3.010e+02 3.550e+02 3.450e+02 3.530e+02 3.580e+02 1.200e+01 3.420e+02
 3.390e+02 2.400e+01 3.000e+00 2.200e+01 2.300e+01 1.600e+01 1.400e+01
 2.000e+01 2.100e+01 1.800e+01 1.900e+01 1.700e+01 1.500e+01 7.000e+00
 1.100e+01 1.300e+01 1.000e+00 4.000e+00 2.000e+00 0.000e+00 9.000e+00
 1.000e+01 5.170e+02 5.150e+02 5.110e+02 5.250e+02 5.270e+02 5.280e+02
 5.050e+02 4.880e+02 5.030e+02 5.130e+02 4.700e+02 4.340e+02 4.280e+02
 4.440e+02 4.310e+02 4.470e+02 4.580e+02 4.540e+02 5.160e+02 5.070e+02
 5.220e+02 5.300e+02 5.180e+02 4.840e+02 4.980e+02 3.630e+02 3.690e+02
 3.760e+02 3.770e+02 3.710e+02 3.590e+02 3.400e+02 3.540e+02 3.520e+02
 3.720e+02 3.230e+02 3.840e+02 3.800e+02 3.670e+02 3.560e+02 3.870e+02
 3.620e+02 3.700e+02 3.900e+02 3.650e+02 3.790e+02 3.750e+02 3.730e+02
 3.480e+02 3.740e+02 3.330e+02 3.570e+02 3.500e+02 3.660e+02 3.980e+02
 3.490e+02 3.470e+02 4.170e+02 4.090e+02 4.220e+02 4.130e+02 4.300e+02
 4.150e+02 4.420e+02 4.490e+02 4.020e+02 4.190e+02 4.390e+02 3.460e+02
 3.680e+02 3.370e+02 3.780e+02 4.240e+02 4.200e+02 3.640e+02 3.600e+02
 3.850e+02 3.960e+02 4.000e+02 3.950e+02 3.810e+02 3.860e+02 3.880e+02
 4.260e+02 3.610e+02 3.890e+02 4.010e+02 4.040e+02 3.820e+02 3.970e+02
 3.930e+02 3.830e+02 4.860e+02 5.720e+02 5.690e+02 4.920e+02 5.680e+02
 5.600e+02 5.630e+02 5.760e+02 4.710e+02 5.890e+02 5.000e+02 5.810e+02
 4.790e+02 5.870e+02 4.770e+02 4.750e+02 4.630e+02 4.380e+02 4.120e+02
 4.900e+02 4.810e+02 4.640e+02 4.680e+02 4.830e+02 5.330e+02 4.720e+02
 4.850e+02 4.960e+02 4.070e+02 4.910e+02 5.060e+02 4.100e+02 5.380e+02
 5.340e+02 5.430e+02 5.370e+02 5.290e+02 5.410e+02 5.120e+02 5.390e+02
 5.480e+02 4.160e+02 4.140e+02 4.670e+02 4.890e+02 3.940e+02 3.990e+02
 4.510e+02 4.320e+02 8.000e+00 3.910e+02 4.740e+02 4.650e+02 4.940e+02
 6.050e+02 3.920e+02 5.190e+02 6.170e+02 6.210e+02 6.290e+02 6.160e+02
 4.110e+02 6.260e+02 6.070e+02 4.780e+02 6.360e+02 4.250e+02 6.000e+02
 4.730e+02 6.020e+02 5.940e+02 4.180e+02 6.060e+02 4.590e+02 6.310e+02
 4.080e+02 6.280e+02 4.270e+02 4.060e+02 4.230e+02 4.800e+02 5.700e+02
 4.450e+02 6.270e+02 5.830e+02 5.540e+02 5.490e+02 5.750e+02 5.920e+02
 5.790e+02 5.650e+02 5.850e+02 6.000e+00 5.460e+02 5.100e+02 5.040e+02
 4.480e+02 4.560e+02 4.950e+02 5.080e+02 4.430e+02 4.500e+02 4.400e+02
 4.360e+02 4.460e+02 4.330e+02 5.420e+02 5.840e+02 5.800e+02 5.710e+02
 4.530e+02 6.090e+02 5.740e+02 5.670e+02 5.590e+02 5.020e+02 4.370e+02
 4.620e+02 4.970e+02 4.990e+02 4.870e+02 4.550e+02 5.010e+02 4.760e+02
 4.820e+02 4.520e+02 5.400e+02 5.470e+02 5.350e+02 5.140e+02 5.450e+02
 5.500e+02 5.440e+02 4.690e+02 4.660e+02 6.420e+02 5.990e+02 6.390e+02
 4.930e+02 6.640e+02 6.490e+02 6.150e+02 6.440e+02 6.480e+02 6.120e+02
 5.730e+02 6.370e+02 6.200e+02 6.030e+02 4.610e+02 6.240e+02 6.220e+02
 6.190e+02 5.960e+02 5.640e+02 5.000e+00 5.310e+02 4.210e+02 4.410e+02
 4.600e+02 5.210e+02 5.260e+02 4.350e+02 4.050e+02 4.290e+02 4.030e+02
 5.560e+02 5.860e+02 5.610e+02 5.530e+02 5.770e+02 5.360e+02 4.570e+02
 5.780e+02 5.570e+02 5.520e+02 6.040e+02 6.180e+02 6.110e+02 6.410e+02
 6.340e+02 6.520e+02 6.450e+02 6.540e+02 6.550e+02 6.130e+02 6.320e+02
 6.510e+02 5.550e+02 5.620e+02 5.090e+02 5.660e+02 5.230e+02 5.950e+02
 6.010e+02 6.080e+02 6.230e+02 5.930e+02 5.580e+02 5.200e+02 5.970e+02
 5.900e+02 6.100e+02 5.240e+02 5.910e+02 5.980e+02 5.510e+02 5.880e+02
 5.320e+02 7.330e+02 1.091e+03 5.820e+02 6.140e+02 6.300e+02 6.350e+02]
Column 'ArrDelay' has 1128 unique values:
[ -14.    2.   14. ...  880. 1279.  991.]
Column 'DepDelay' has 1058 unique values:
[  8.  19.  34. ... 956. 810. 925.]
Column 'Origin' has 303 unique values:
['IAD' 'IND' 'ISP' 'JAN' 'JAX' 'LAS' 'LAX' 'LBB' 'LIT' 'MAF' 'MCI' 'MCO'
 'MDW' 'MHT' 'MSY' 'OAK' 'OKC' 'OMA' 'ONT' 'ORF' 'PBI' 'PDX' 'PHL' 'PHX'
 'PIT' 'PVD' 'RDU' 'RNO' 'RSW' 'SAN' 'SAT' 'SDF' 'SEA' 'SFO' 'SJC' 'SLC'
 'SMF' 'SNA' 'STL' 'TPA' 'TUL' 'TUS' 'ABQ' 'ALB' 'AMA' 'AUS' 'BDL' 'BHM'
 'BNA' 'BOI' 'BUF' 'BUR' 'BWI' 'CLE' 'CMH' 'CRP' 'DAL' 'DEN' 'DTW' 'ELP'
 'FLL' 'GEG' 'HOU' 'HRL' 'ROC' 'ORD' 'EWR' 'SYR' 'IAH' 'CRW' 'FAT' 'COS'
 'MRY' 'LGB' 'BFL' 'EUG' 'ICT' 'MEM' 'BTV' 'MKE' 'LFT' 'BRO' 'PWM' 'MSP'
 'SRQ' 'CLT' 'CVG' 'GSO' 'SHV' 'DCA' 'TYS' 'GSP' 'RIC' 'DFW' 'BGR' 'DAY'
 'GRR' 'CHS' 'CAE' 'TLH' 'XNA' 'GPT' 'VPS' 'LGA' 'ATL' 'MSN' 'SAV' 'BTR'
 'LEX' 'LRD' 'MOB' 'MTJ' 'GRK' 'AEX' 'PNS' 'ABE' 'HSV' 'CHA' 'MFE' 'MLU'
 'DSM' 'MGM' 'AVL' 'LCH' 'BOS' 'MYR' 'CLL' 'DAB' 'ASE' 'ATW' 'BMI' 'CAK'
 'CID' 'CPR' 'EGE' 'FLG' 'FSD' 'FWA' 'GJT' 'GRB' 'HNL' 'KOA' 'LAN' 'LIH'
 'MBS' 'MDT' 'MFR' 'OGG' 'PSP' 'RAP' 'ROA' 'SBA' 'SBN' 'SPI' 'TEX' 'YUM'
 'AVP' 'CWA' 'DRO' 'ILM' 'ITO' 'JFK' 'TVC' 'HDN' 'SBP' 'CLD' 'HPN' 'MIA'
 'SGF' 'TRI' 'SUN' 'SGU' 'SLE' 'MSO' 'BZN' 'YKM' 'GTF' 'BIL' 'JAC' 'MOD'
 'FAR' 'GUC' 'AZO' 'PIA' 'MLI' 'LNK' 'FCA' 'IDA' 'BIS' 'PSC' 'COD' 'TWF'
 'RDM' 'HLN' 'RDD' 'PIH' 'EKO' 'LWS' 'SMX' 'ACV' 'OXR' 'CEC' 'CIC' 'PMD'
 'RFD' 'BTM' 'IYK' 'IPL' 'BLI' 'CDC' 'SJU' 'STT' 'ANC' 'STX' 'MLB' 'PHF'
 'PFN' 'FAY' 'AGS' 'GNV' 'ABY' 'DHN' 'EVV' 'FNT' 'OAJ' 'TOL' 'SWF' 'EWN'
 'MEI' 'GTR' 'LYH' 'HHH' 'EYW' 'VLD' 'CSG' 'ACY' 'FSM' 'MCN' 'CHO' 'FLO'
 'BQK' 'SCE' 'TUP' 'TYR' 'LAW' 'SPS' 'ABI' 'GGG' 'ACT' 'SJT' 'TXK' 'CMI'
 'ROW' 'RST' 'MQT' 'LSE' 'DBQ' 'GFK' 'MOT' 'DLH' 'SUX' 'PLN' 'BGM' 'ERI'
 'ALO' 'CMX' 'RHI' 'ELM' 'JNU' 'KTN' 'SIT' 'PSG' 'CDV' 'YAK' 'BRW' 'OME'
 'OTZ' 'BET' 'FAI' 'SCC' 'ADQ' 'WRG' 'ADK' 'PSE' 'BQN' 'BPT' 'RKS' 'GCC'
 'MKG' 'DLG' 'AKN' 'LWB' 'ACK' 'WYS' 'BJI' 'INL' 'GST' 'PUB' 'OTH' 'LMT'
 'ITH' 'HTS' 'PIR']

Column 'Dest' has 304 unique values:
['TPA' 'BWI' 'JAX' 'LAS' 'MCO' 'MDW' 'PHX' 'FLL' 'PBI' 'RSW' 'HOU' 'BHM'
 'BNA' 'IND' 'PHL' 'ABQ' 'ALB' 'AMA' 'AUS' 'BDL' 'BOI' 'BUF' 'BUR' 'CLE'
 'CMH' 'DEN' 'ELP' 'GEG' 'IAD' 'ISP' 'LAX' 'LBB' 'LIT' 'MAF' 'MCI' 'MHT'
 'MSY' 'OAK' 'OKC' 'OMA' 'ONT' 'ORF' 'PDX' 'PIT' 'PVD' 'RDU' 'RNO' 'SAN'
 'SAT' 'SDF' 'SEA' 'SFO' 'SJC' 'SLC' 'SMF' 'SNA' 'STL' 'TUL' 'TUS' 'DAL'
 'DTW' 'JAN' 'HRL' 'CRP' 'EWR' 'IAH' 'ROC' 'MYR' 'GSO' 'SAV' 'RIC' 'COS'
 'FAT' 'MRY' 'LGB' 'BFL' 'EUG' 'ICT' 'CAE' 'DFW' 'DAY' 'MSP' 'GSP' 'MEM'
 'TYS' 'SHV' 'BTV' 'MFE' 'PWM' 'ATL' 'SYR' 'MKE' 'HSV' 'BTR' 'CHS' 'MSN'
 'LFT' 'LRD' 'SRQ' 'CLT' 'VPS' 'AVL' 'GPT' 'LGA' 'ABE' 'BGR' 'DCA' 'ORD'
 'GRR' 'MOB' 'PNS' 'CHA' 'MGM' 'CVG' 'GRK' 'PSP' 'TLH' 'LCH' 'BOS' 'BRO'
 'XNA' 'BPT' 'LEX' 'MTJ' 'AEX' 'MLU' 'DSM' 'CRW' 'CLL' 'ILM' 'JFK' 'ASE'
 'CPR' 'DRO' 'RAP' 'KOA' 'LIH' 'OGG' 'MDT' 'ROA' 'SPI' 'HNL' 'MFR' 'ATW'
 'BMI' 'CAK' 'CID' 'FSD' 'FWA' 'GRB' 'LAN' 'MBS' 'SBN' 'FLG' 'GJT' 'YUM'
 'EGE' 'ITO' 'AVP' 'CWA' 'TVC' 'SBP' 'SBA' 'COD' 'HDN' 'TEX' 'CLD' 'MLB'
 'SGF' 'MIA' 'HPN' 'TRI' 'SUN' 'SGU' 'TWF' 'IDA' 'MSO' 'BZN' 'YKM' 'SLE'
 'HLN' 'LWS' 'GTF' 'BIL' 'BTM' 'JAC' 'FCA' 'PSC' 'ACV' 'RDD' 'IPL' 'MOD'
 'PIA' 'LNK' 'GUC' 'AZO' 'FAR' 'MLI' 'PMD' 'BIS' 'PIH' 'EKO' 'RDM' 'BLI'
 'IYK' 'SMX' 'CEC' 'CIC' 'OXR' 'RFD' 'CDC' 'OGD' 'STT' 'SJU' 'ANC' 'STX'
 'DAB' 'PHF' 'MCN' 'VLD' 'CSG' 'SWF' 'BQK' 'MEI' 'FAY' 'EWN' 'SCE' 'DHN'
 'EYW' 'EVV' 'PFN' 'GNV' 'FNT' 'AGS' 'ABY' 'CHO' 'OAJ' 'FSM' 'FLO' 'HHH'
 'TOL' 'LYH' 'GTR' 'ACY' 'TUP' 'LAW' 'TYR' 'ABI' 'TXK' 'ACT' 'SPS' 'SJT'
 'GGG' 'CMI' 'ROW' 'MQT' 'RST' 'LSE' 'DBQ' 'DLH' 'GFK' 'MOT' 'RHI' 'SUX'
 'CMX' 'BGM' 'PLN' 'ERI' 'ALO' 'ELM' 'KTN' 'SIT' 'JNU' 'CDV' 'PSG' 'YAK'
 'WRG' 'FAI' 'OME' 'BRW' 'SCC' 'OTZ' 'BET' 'ADQ' 'ADK' 'PSE' 'BQN' 'GCC'
 'RKS' 'CYS' 'MKG' 'DLG' 'AKN' 'LWB' 'ACK' 'WYS' 'INL' 'BJI' 'GST' 'LMT'
 'OTH' 'ITH' 'HTS' 'PIR']
Column 'Distance' has 1419 unique values:
[ 810  515  688 ...  902 1746  890]
Column 'TaxiIn' has 180 unique values:
[  4.   5.   3.   6.   7.   2.   9.   8.  40.  16.  11.  62.  23.  28.
  22.  14.  18.  25.  64.  21.  13.  10.  20.  19.  12.   1.  17.  32.
  27.  15.  39.  24.  33.  34.  nan  31.  35.  45.  37.  30.  29.  44.
  26.  36.  48.  89.  52.  41.  91.  54.  66.  65.  57.  47.  59.  43.
  49.  85. 123.  46. 132.  58.  50.  76.  70. 114.  42.  38.  99. 150.
   0.  81.  67.  55.  51. 105.  71. 125.  93.  96.  90.  87.  60. 143.
  88. 100.  61.  73. 115. 121.  86. 101. 145. 167. 133. 113.  56.  75.
  79.  92.  95. 146.  53.  97.  78.  83.  82.  63.  77.  80.  69.  68.
  84. 152. 126. 189. 151.  94. 120.  74.  72. 106. 128. 129. 107. 109.
 124. 163. 160. 136. 131. 154. 148. 117. 110. 111. 159. 135. 175. 147.
 141. 157. 176.  98. 138. 200. 122. 119. 207. 199. 103. 112. 104. 102.
 144. 137. 165. 174. 156. 149. 184. 130. 178. 116. 118. 134. 153. 158.
 225. 170. 240. 186. 197. 127. 140. 179. 139. 171. 108. 161. 173.]
Column 'TaxiOut' has 332 unique values:
[  8.  10.  17.   7.  19.   9.  16.   5.   6.  11.  12.  14.  15.  28.
  13.  22.  18.  24.  21.  30.  20.  32.  23.  85.  29.  52.  44.   4.
  33.  25.  26.  27.  50.   3.   1.  37.  42.  31.  35.  40.  38.  45.
  47.  39.  41.  34.  46.  36.  51.  49.   2.  61.  67.  48.  43.  64.
  66.  63.  59. 113.  78.  92.  90.  55.  58.  56.  79.  77.  69.  53.
  72.  62.  76.  65.  75.  57.  71.  73.  68.  60.  83.  54. 104. 107.
 101.  70.  93.  81.  94.  80.  74. 150.  86. 105.  97. 110. 127. 129.
  82. 108. 139. 115.  87.  84. 170. 154. 119. 102. 120. 178. 106. 103.
 151. 128. 112.  99.  88. 147. 131. 159. 124. 123. 109. 100. 137.  96.
 116.  95. 117.  89. 126. 138.  98.  91. 114. 157. 122. 118. 142. 133.
 164. 145. 149. 221. 153. 140. 163. 143. 162. 203. 167. 173. 130. 144.
 111. 125. 166. 177. 193. 190. 121. 141. 247. 266. 251. 233. 234. 262.
 318. 155. 287. 186. 298. 158. 383. 379. 320. 300. 306. 248. 168. 309.
 289. 271. 191. 218. 160. 165. 132. 152. 176. 134. 200.   0. 228. 278.
 288. 182. 244. 225. 206. 299. 257. 188. 322. 268. 148. 236. 208. 194.
 217. 201. 204. 136. 135. 156. 161. 146. 185. 202. 180. 172. 224. 209.
 220. 183. 187. 305. 330. 263. 210. 169. 199. 181. 195. 198. 205. 223.
 219. 227. 243. 184. 171. 192. 196. 175. 212. 238. 179. 241. 216. 189.
 197. 331. 335. 267. 226. 213. 231. 269. 229. 285. 256. 174. 246. 281.
 249. 222. 259. 237. 215. 211. 207. 214. 261. 364. 232. 326. 235. 230.
 274. 292. 290. 301. 282. 303. 276. 272. 240. 258. 280. 316. 345. 242.
 273. 245. 319. 337. 325. 252. 260. 277. 279. 264. 422. 291. 254. 284.
 250. 304. 356. 239. 265. 270. 283.  nan 308. 302. 327. 393. 336. 353.
 321. 342. 371. 255. 324. 386. 376. 312. 362. 286. 370.]
Column 'Cancelled' has 2 unique values:
[0 1]
Column 'CancellationCode' has 4 unique values:
['N' 'A' 'B' 'C']
Column 'Diverted' has 2 unique values:
[0 1]
Column 'CarrierDelay' has 983 unique values:
[      nan 2.000e+00 1.000e+01 8.000e+00 3.000e+00 0.000e+00 1.200e+01
 7.000e+00 4.000e+01 5.000e+00 2.820e+02 2.600e+01 1.000e+00 1.100e+01
 1.500e+01 5.000e+01 2.300e+01 1.900e+01 1.800e+01 9.000e+00 4.800e+01
 1.700e+01 2.000e+01 4.000e+00 1.140e+02 6.000e+00 3.200e+01 1.300e+01
 1.600e+01 6.100e+01 2.500e+01 2.700e+01 1.400e+01 5.900e+01 6.000e+01
 2.100e+01 4.500e+01 3.800e+01 2.400e+01 1.920e+02 3.400e+01 3.900e+01
 2.200e+01 2.900e+01 6.900e+01 1.840e+02 2.850e+02 8.500e+01 3.000e+01
 3.100e+01 4.600e+01 3.300e+01 6.800e+01 3.700e+01 2.800e+01 3.600e+01
 7.500e+01 5.100e+01 5.800e+01 2.200e+02 5.500e+01 5.700e+01 3.500e+01
 4.300e+01 6.500e+01 8.200e+01 4.900e+01 4.700e+01 4.100e+01 1.000e+02
 6.300e+01 7.700e+01 5.200e+01 1.320e+02 4.400e+01 5.400e+01 9.200e+01
 2.660e+02 2.000e+02 8.600e+01 9.400e+01 6.400e+01 8.300e+01 9.000e+01
 6.600e+01 1.170e+02 9.800e+01 7.400e+01 1.220e+02 4.200e+01 1.680e+02
 1.560e+02 5.600e+01 6.700e+01 6.200e+01 1.050e+02 1.640e+02 1.200e+02
 9.700e+01 8.000e+01 5.300e+01 1.330e+02 1.030e+02 1.040e+02 1.960e+02
 1.020e+02 7.000e+01 7.200e+01 1.780e+02 1.380e+02 8.700e+01 1.520e+02
 2.690e+02 1.190e+02 1.670e+02 8.100e+01 7.600e+01 9.900e+01 8.800e+01
 1.270e+02 1.570e+02 1.910e+02 7.100e+01 1.260e+02 1.880e+02 7.300e+01
 9.100e+01 2.770e+02 1.750e+02 8.400e+01 1.110e+02 9.300e+01 2.500e+02
 1.290e+02 9.500e+01 1.090e+02 1.530e+02 1.120e+02 1.600e+02 7.900e+01
 1.440e+02 1.060e+02 1.450e+02 1.070e+02 2.160e+02 1.490e+02 1.010e+02
 1.480e+02 1.230e+02 8.900e+01 1.310e+02 1.500e+02 1.280e+02 9.600e+01
 7.800e+01 2.540e+02 1.240e+02 1.250e+02 1.350e+02 3.610e+02 1.100e+02
 1.080e+02 1.180e+02 1.150e+02 2.110e+02 3.470e+02 1.400e+02 1.810e+02
 2.620e+02 3.140e+02 1.130e+02 3.200e+02 2.080e+02 1.390e+02 1.420e+02
 1.590e+02 1.210e+02 1.370e+02 2.990e+02 1.990e+02 2.320e+02 2.020e+02
 2.330e+02 2.120e+02 2.930e+02 1.700e+02 2.100e+02 2.840e+02 1.360e+02
 1.820e+02 2.260e+02 1.850e+02 1.800e+02 4.310e+02 2.380e+02 2.610e+02
 2.420e+02 1.940e+02 1.930e+02 3.730e+02 4.120e+02 1.460e+02 1.650e+02
 1.620e+02 2.590e+02 2.580e+02 3.220e+02 1.430e+02 2.430e+02 1.760e+02
 2.480e+02 1.470e+02 1.740e+02 5.020e+02 2.240e+02 1.690e+02 1.410e+02
 2.250e+02 4.610e+02 2.750e+02 2.040e+02 2.190e+02 3.310e+02 3.110e+02
 1.160e+02 1.720e+02 2.410e+02 2.340e+02 1.630e+02 6.040e+02 2.830e+02
 2.950e+02 2.280e+02 2.370e+02 2.490e+02 1.900e+02 2.010e+02 2.210e+02
 2.520e+02 6.260e+02 2.360e+02 1.950e+02 3.480e+02 1.340e+02 1.830e+02
 1.770e+02 3.130e+02 4.510e+02 2.700e+02 2.790e+02 3.030e+02 4.060e+02
 4.190e+02 1.610e+02 3.120e+02 1.790e+02 4.160e+02 4.650e+02 1.540e+02
 6.520e+02 1.550e+02 1.730e+02 1.660e+02 1.970e+02 2.090e+02 2.130e+02
 2.070e+02 1.890e+02 1.300e+02 1.510e+02 2.140e+02 2.270e+02 2.310e+02
 1.980e+02 2.630e+02 2.600e+02 2.530e+02 2.300e+02 4.050e+02 2.550e+02
 1.860e+02 1.580e+02 2.050e+02 2.290e+02 2.030e+02 2.180e+02 3.910e+02
 3.240e+02 2.680e+02 4.090e+02 2.230e+02 3.370e+02 2.440e+02 3.500e+02
 3.260e+02 3.070e+02 3.100e+02 2.670e+02 3.300e+02 3.780e+02 1.870e+02
 2.810e+02 4.040e+02 2.170e+02 2.740e+02 3.620e+02 1.710e+02 2.960e+02
 2.060e+02 3.460e+02 2.220e+02 2.640e+02 3.430e+02 2.860e+02 2.150e+02
 2.920e+02 3.250e+02 4.520e+02 5.600e+02 3.060e+02 3.020e+02 6.060e+02
 4.000e+02 2.560e+02 2.350e+02 4.010e+02 5.780e+02 2.390e+02 2.470e+02
 2.460e+02 3.530e+02 2.720e+02 2.730e+02 2.400e+02 2.780e+02 3.170e+02
 3.320e+02 3.930e+02 2.710e+02 2.650e+02 3.870e+02 2.450e+02 6.320e+02
 2.880e+02 3.550e+02 3.660e+02 6.310e+02 3.340e+02 2.890e+02 3.560e+02
 1.032e+03 3.600e+02 2.570e+02 3.940e+02 4.500e+02 3.710e+02 3.850e+02
 3.760e+02 3.540e+02 2.510e+02 4.080e+02 3.150e+02 3.650e+02 4.930e+02
 3.000e+02 4.420e+02 2.910e+02 4.230e+02 3.350e+02 3.380e+02 5.550e+02
 2.900e+02 2.800e+02 3.840e+02 4.170e+02 3.570e+02 3.980e+02 4.330e+02
 3.700e+02 3.390e+02 4.790e+02 3.770e+02 4.430e+02 6.990e+02 3.990e+02
 2.870e+02 4.600e+02 6.130e+02 5.290e+02 5.750e+02 3.630e+02 6.830e+02
 5.560e+02 3.800e+02 4.530e+02 7.750e+02 3.920e+02 6.820e+02 6.770e+02
 6.280e+02 3.640e+02 8.560e+02 7.440e+02 4.100e+02 3.040e+02 3.720e+02
 5.850e+02 6.300e+02 5.000e+02 5.500e+02 4.750e+02 7.850e+02 4.740e+02
 5.610e+02 3.290e+02 6.880e+02 4.720e+02 4.410e+02 5.870e+02 7.810e+02
 4.680e+02 6.340e+02 3.580e+02 5.160e+02 5.300e+02 5.710e+02 3.510e+02
 6.090e+02 4.260e+02 4.860e+02 3.950e+02 6.620e+02 4.210e+02 4.900e+02
 5.810e+02 5.470e+02 4.540e+02 5.350e+02 7.430e+02 8.580e+02 3.520e+02
 4.130e+02 5.660e+02 9.030e+02 1.120e+03 8.880e+02 3.450e+02 5.820e+02
 3.410e+02 7.720e+02 7.640e+02 4.440e+02 7.600e+02 4.140e+02 1.017e+03
 3.050e+02 6.490e+02 8.650e+02 5.760e+02 6.630e+02 2.980e+02 3.820e+02
 7.770e+02 5.270e+02 3.090e+02 5.910e+02 6.790e+02 7.290e+02 5.450e+02
 3.160e+02 5.040e+02 4.340e+02 3.180e+02 4.580e+02 7.560e+02 4.490e+02
 1.094e+03 4.450e+02 3.740e+02 3.810e+02 3.080e+02 4.550e+02 8.050e+02
 9.730e+02 3.750e+02 7.700e+02 4.880e+02 8.770e+02 7.550e+02 1.036e+03
 3.400e+02 1.068e+03 9.630e+02 1.024e+03 4.980e+02 6.600e+02 4.030e+02
 4.250e+02 7.570e+02 3.690e+02 3.280e+02 4.020e+02 7.190e+02 7.000e+02
 1.014e+03 1.158e+03 5.330e+02 2.940e+02 4.840e+02 3.230e+02 3.360e+02
 3.900e+02 5.700e+02 5.950e+02 5.620e+02 3.270e+02 6.570e+02 3.590e+02
 4.560e+02 4.070e+02 4.300e+02 4.960e+02 4.370e+02 3.830e+02 3.190e+02
 8.380e+02 4.110e+02 5.070e+02 4.640e+02 3.880e+02 4.290e+02 4.800e+02
 1.089e+03 5.240e+02 3.420e+02 5.100e+02 5.400e+02 2.760e+02 3.010e+02
 7.100e+02 4.180e+02 4.870e+02 4.810e+02 3.210e+02 5.010e+02 5.390e+02
 4.240e+02 7.480e+02 4.760e+02 8.520e+02 6.030e+02 4.570e+02 6.400e+02
 6.750e+02 8.230e+02 4.590e+02 4.970e+02 7.760e+02 9.400e+02 4.770e+02
 3.890e+02 5.730e+02 8.290e+02 6.680e+02 5.230e+02 4.280e+02 5.590e+02
 3.860e+02 6.430e+02 8.760e+02 6.510e+02 6.350e+02 5.120e+02 7.590e+02
 2.970e+02 5.340e+02 3.440e+02 5.460e+02 9.470e+02 7.110e+02 5.830e+02
 1.351e+03 1.064e+03 1.065e+03 4.470e+02 5.970e+02 5.090e+02 6.180e+02
 8.990e+02 1.348e+03 4.690e+02 4.270e+02 6.230e+02 5.140e+02 3.670e+02
 9.820e+02 8.390e+02 9.410e+02 1.455e+03 7.710e+02 1.076e+03 1.200e+03
 1.107e+03 7.320e+02 5.740e+02 9.750e+02 7.340e+02 1.019e+03 9.550e+02
 4.350e+02 9.080e+02 7.270e+02 7.580e+02 6.730e+02 5.510e+02 6.110e+02
 7.400e+02 1.091e+03 9.060e+02 9.590e+02 5.360e+02 7.370e+02 9.180e+02
 4.830e+02 3.330e+02 3.680e+02 6.450e+02 8.590e+02 8.070e+02 8.620e+02
 6.410e+02 4.630e+02 3.960e+02 4.360e+02 1.061e+03 1.312e+03 1.086e+03
 4.990e+02 6.640e+02 5.150e+02 4.620e+02 8.810e+02 1.001e+03 4.380e+02
 3.490e+02 3.970e+02 5.430e+02 5.050e+02 4.220e+02 5.250e+02 5.530e+02
 7.050e+02 6.250e+02 4.480e+02 5.060e+02 9.900e+02 9.090e+02 6.890e+02
 4.460e+02 4.400e+02 4.670e+02 5.800e+02 4.200e+02 7.950e+02 7.900e+02
 5.380e+02 6.590e+02 5.410e+02 6.540e+02 8.030e+02 5.320e+02 1.090e+03
 5.130e+02 8.320e+02 5.960e+02 1.160e+03 7.940e+02 8.550e+02 9.790e+02
 7.120e+02 7.200e+02 1.011e+03 1.224e+03 5.580e+02 5.720e+02 6.660e+02
 7.180e+02 1.198e+03 5.180e+02 1.166e+03 6.810e+02 1.131e+03 7.330e+02
 7.080e+02 5.210e+02 8.310e+02 6.470e+02 7.610e+02 1.490e+03 7.530e+02
 4.910e+02 6.700e+02 6.420e+02 5.190e+02 5.640e+02 8.010e+02 5.200e+02
 5.900e+02 6.140e+02 7.260e+02 8.170e+02 1.026e+03 6.170e+02 1.084e+03
 6.000e+02 1.000e+03 1.172e+03 7.840e+02 7.380e+02 8.450e+02 9.040e+02
 3.790e+02 5.990e+02 6.050e+02 4.320e+02 6.120e+02 4.780e+02 6.200e+02
 5.420e+02 6.870e+02 4.920e+02 8.190e+02 7.030e+02 1.268e+03 5.790e+02
 8.510e+02 7.780e+02 7.130e+02 8.270e+02 5.440e+02 8.060e+02 8.840e+02
 6.980e+02 6.080e+02 7.070e+02 6.460e+02 1.139e+03 5.880e+02 1.249e+03
 1.015e+03 8.790e+02 1.044e+03 4.710e+02 1.075e+03 8.350e+02 6.850e+02
 1.046e+03 1.291e+03 5.930e+02 5.630e+02 7.220e+02 7.170e+02 1.542e+03
 7.690e+02 1.057e+03 1.395e+03 7.520e+02 2.436e+03 7.360e+02 6.150e+02
 6.530e+02 5.520e+02 5.680e+02 8.640e+02 1.104e+03 8.680e+02 6.010e+02
 8.340e+02 7.300e+02 6.220e+02 4.700e+02 6.670e+02 6.710e+02 6.270e+02
 4.940e+02 5.670e+02 8.630e+02 6.240e+02 9.320e+02 1.129e+03 7.630e+02
 6.290e+02 6.550e+02 7.990e+02 7.460e+02 7.140e+02 5.370e+02 1.203e+03
 1.292e+03 5.540e+02 1.258e+03 1.126e+03 1.111e+03 7.930e+02 1.951e+03
 8.860e+02 4.390e+02 4.850e+02 1.171e+03 1.141e+03 4.660e+02 9.280e+02
 6.440e+02 6.840e+02 1.096e+03 5.860e+02 8.700e+02 9.310e+02 1.043e+03
 5.490e+02 6.650e+02 6.690e+02 7.490e+02 6.330e+02 6.610e+02 8.980e+02
 1.707e+03 7.060e+02 9.110e+02 1.029e+03 9.100e+02 4.150e+02 9.570e+02
 1.040e+03 8.140e+02 5.940e+02 1.059e+03 1.165e+03 9.920e+02 1.344e+03
 9.700e+02 5.080e+02 1.186e+03 1.079e+03 1.055e+03 1.016e+03 6.780e+02
 7.670e+02 8.960e+02 8.830e+02 4.950e+02 7.230e+02 1.056e+03 4.890e+02
 7.890e+02 5.280e+02 7.020e+02 6.070e+02 6.960e+02 6.580e+02 5.770e+02
 8.100e+02 1.175e+03 1.082e+03 8.920e+02 9.600e+02 9.680e+02 6.480e+02
 6.760e+02 6.390e+02 6.940e+02 9.660e+02 5.030e+02 8.090e+02 9.450e+02
 8.210e+02 7.980e+02 7.040e+02 6.210e+02 1.510e+03 8.890e+02 8.370e+02
 8.720e+02 1.127e+03 6.900e+02 1.263e+03 9.140e+02 5.310e+02 8.220e+02
 7.510e+02 7.150e+02 6.910e+02 5.650e+02 8.900e+02 6.160e+02 1.045e+03
 4.730e+02 7.650e+02 6.020e+02 4.820e+02 5.920e+02 5.690e+02 5.220e+02
 1.124e+03 7.390e+02 7.500e+02 8.460e+02 5.170e+02 8.120e+02 1.359e+03
 5.840e+02 6.360e+02 6.930e+02 1.072e+03 7.010e+02 8.480e+02 9.020e+02
 8.000e+02 1.069e+03 1.020e+03 6.500e+02 1.286e+03 8.930e+02 8.420e+02
 7.790e+02 6.800e+02 5.570e+02 7.820e+02 1.168e+03 1.552e+03 1.382e+03
 9.330e+02 1.183e+03 8.490e+02 1.018e+03 6.720e+02 6.100e+02 1.369e+03
 6.970e+02 6.190e+02 8.130e+02 9.240e+02 9.540e+02 1.346e+03 1.146e+03
 9.560e+02 5.110e+02 1.230e+03 7.540e+02 7.470e+02 9.810e+02 8.610e+02
 1.081e+03 9.770e+02 9.880e+02 6.740e+02 8.600e+02 8.670e+02 1.194e+03
 9.500e+02 5.260e+02 1.003e+03 9.530e+02 8.470e+02 9.150e+02 8.690e+02
 1.092e+03 1.307e+03 8.870e+02 1.190e+03 8.540e+02 8.750e+02 1.038e+03
 7.740e+02 7.860e+02 9.970e+02 1.108e+03 7.350e+02 9.930e+02 1.170e+03
 9.740e+02 9.430e+02 7.210e+02 9.050e+02]
Column 'WeatherDelay' has 599 unique values:
[      nan 0.000e+00 2.400e+01 1.200e+01 2.200e+01 7.000e+00 2.500e+01
 1.350e+02 3.000e+00 1.000e+00 1.100e+01 4.000e+00 1.300e+01 5.000e+00
 8.100e+01 7.800e+01 7.200e+01 2.100e+01 8.000e+00 3.700e+01 5.500e+01
 1.570e+02 2.000e+00 2.020e+02 2.600e+01 6.800e+01 2.300e+01 4.800e+01
 3.200e+01 4.600e+01 3.300e+01 6.000e+01 5.400e+01 1.890e+02 1.980e+02
 1.000e+01 3.800e+01 7.000e+01 1.160e+02 3.100e+01 6.000e+00 1.800e+01
 7.700e+01 1.200e+02 6.300e+01 1.170e+02 5.000e+01 1.600e+01 1.700e+01
 3.000e+01 8.500e+01 4.300e+01 9.300e+01 1.500e+02 1.490e+02 4.000e+01
 7.600e+01 2.000e+01 1.180e+02 3.500e+01 6.600e+01 5.200e+01 1.130e+02
 1.500e+01 5.300e+01 4.200e+01 7.100e+01 3.600e+01 7.500e+01 1.400e+01
 2.220e+02 1.420e+02 6.500e+01 9.700e+01 2.330e+02 2.900e+01 8.000e+01
 5.600e+01 6.400e+01 3.400e+01 5.800e+01 8.700e+01 2.800e+01 9.000e+00
 6.700e+01 1.680e+02 4.900e+01 4.500e+01 1.000e+02 4.100e+01 1.480e+02
 1.050e+02 1.360e+02 1.610e+02 1.590e+02 1.670e+02 9.000e+01 1.710e+02
 1.660e+02 3.900e+01 4.400e+01 1.250e+02 1.900e+01 8.800e+01 1.750e+02
 7.400e+01 1.010e+02 8.900e+01 1.690e+02 8.400e+01 1.090e+02 1.390e+02
 4.700e+01 1.990e+02 2.230e+02 1.110e+02 2.700e+01 1.100e+02 5.900e+01
 5.100e+01 6.100e+01 1.800e+02 6.900e+01 9.100e+01 1.850e+02 1.430e+02
 8.200e+01 5.700e+01 1.070e+02 8.300e+01 9.200e+01 1.450e+02 2.300e+02
 1.080e+02 1.340e+02 1.460e+02 1.370e+02 1.920e+02 2.670e+02 1.630e+02
 1.950e+02 1.140e+02 1.270e+02 1.930e+02 1.330e+02 1.260e+02 1.820e+02
 9.400e+01 1.310e+02 1.440e+02 1.190e+02 9.500e+01 1.290e+02 1.400e+02
 9.800e+01 1.240e+02 2.450e+02 7.900e+01 1.150e+02 9.900e+01 1.860e+02
 1.410e+02 8.600e+01 2.310e+02 6.200e+01 1.740e+02 1.320e+02 2.660e+02
 1.880e+02 7.300e+01 4.060e+02 2.800e+02 3.430e+02 1.540e+02 2.350e+02
 1.030e+02 2.030e+02 1.210e+02 1.040e+02 2.080e+02 2.200e+02 1.600e+02
 1.910e+02 2.140e+02 1.760e+02 1.640e+02 2.010e+02 1.060e+02 1.020e+02
 1.280e+02 3.940e+02 3.490e+02 2.340e+02 2.180e+02 2.750e+02 3.440e+02
 1.510e+02 1.940e+02 1.230e+02 2.110e+02 1.120e+02 3.130e+02 1.550e+02
 2.050e+02 1.580e+02 1.520e+02 3.070e+02 2.120e+02 2.100e+02 2.250e+02
 2.940e+02 1.970e+02 1.380e+02 1.730e+02 1.830e+02 3.000e+02 3.100e+02
 1.220e+02 1.900e+02 2.980e+02 1.700e+02 2.420e+02 2.130e+02 2.650e+02
 2.850e+02 1.300e+02 2.150e+02 1.470e+02 4.090e+02 2.280e+02 2.930e+02
 2.210e+02 2.170e+02 3.340e+02 9.600e+01 2.400e+02 5.870e+02 1.840e+02
 1.720e+02 4.400e+02 2.730e+02 2.790e+02 2.430e+02 2.190e+02 2.060e+02
 1.650e+02 2.970e+02 3.050e+02 1.620e+02 1.960e+02 2.610e+02 1.530e+02
 3.700e+02 1.780e+02 2.840e+02 2.710e+02 2.480e+02 2.410e+02 2.550e+02
 2.590e+02 2.380e+02 3.390e+02 3.470e+02 3.250e+02 1.870e+02 1.770e+02
 2.040e+02 3.860e+02 2.680e+02 3.080e+02 2.830e+02 2.530e+02 3.640e+02
 2.000e+02 2.460e+02 2.580e+02 2.630e+02 4.880e+02 3.170e+02 2.870e+02
 3.010e+02 2.600e+02 1.810e+02 3.190e+02 2.690e+02 2.470e+02 3.850e+02
 2.920e+02 4.080e+02 3.310e+02 4.180e+02 4.580e+02 3.650e+02 2.820e+02
 3.480e+02 3.970e+02 3.770e+02 1.560e+02 4.220e+02 2.500e+02 2.370e+02
 2.560e+02 3.350e+02 2.490e+02 3.590e+02 1.790e+02 3.330e+02 2.890e+02
 3.500e+02 3.140e+02 2.720e+02 2.810e+02 4.260e+02 3.760e+02 3.360e+02
 3.240e+02 3.900e+02 3.580e+02 3.990e+02 3.670e+02 2.860e+02 2.540e+02
 7.840e+02 7.410e+02 4.960e+02 5.060e+02 2.960e+02 3.200e+02 3.980e+02
 5.730e+02 8.760e+02 1.049e+03 4.340e+02 4.000e+02 7.500e+02 6.040e+02
 5.390e+02 3.740e+02 4.610e+02 7.440e+02 7.790e+02 2.440e+02 4.670e+02
 5.620e+02 3.030e+02 7.770e+02 2.160e+02 4.160e+02 6.850e+02 2.700e+02
 3.180e+02 4.020e+02 4.900e+02 4.530e+02 3.510e+02 4.890e+02 4.200e+02
 3.420e+02 4.250e+02 2.070e+02 2.320e+02 4.240e+02 3.810e+02 2.090e+02
 2.240e+02 2.270e+02 2.620e+02 2.290e+02 3.520e+02 2.510e+02 3.410e+02
 3.150e+02 3.530e+02 2.260e+02 2.770e+02 3.280e+02 2.570e+02 3.460e+02
 2.880e+02 3.210e+02 2.990e+02 4.520e+02 4.540e+02 4.560e+02 3.560e+02
 5.100e+02 2.760e+02 2.360e+02 3.290e+02 3.020e+02 2.900e+02 3.600e+02
 2.950e+02 2.780e+02 4.550e+02 3.780e+02 4.330e+02 2.740e+02 3.450e+02
 4.320e+02 4.300e+02 2.520e+02 8.460e+02 3.660e+02 3.270e+02 4.920e+02
 3.680e+02 3.630e+02 2.390e+02 4.110e+02 4.140e+02 7.050e+02 5.480e+02
 3.320e+02 4.760e+02 4.980e+02 8.030e+02 5.300e+02 6.680e+02 6.890e+02
 6.530e+02 9.510e+02 3.090e+02 8.680e+02 6.590e+02 1.070e+03 1.080e+03
 7.320e+02 1.148e+03 9.020e+02 3.160e+02 4.210e+02 4.230e+02 3.040e+02
 4.170e+02 4.130e+02 3.300e+02 5.470e+02 2.910e+02 5.140e+02 3.890e+02
 4.640e+02 3.060e+02 2.640e+02 3.220e+02 4.450e+02 3.120e+02 3.400e+02
 3.260e+02 3.230e+02 4.710e+02 3.610e+02 4.190e+02 4.480e+02 5.280e+02
 4.720e+02 5.840e+02 8.470e+02 4.600e+02 5.670e+02 8.720e+02 5.360e+02
 4.290e+02 5.270e+02 4.120e+02 5.420e+02 3.690e+02 4.360e+02 4.790e+02
 4.660e+02 3.790e+02 5.570e+02 5.700e+02 4.440e+02 3.750e+02 4.010e+02
 3.870e+02 1.027e+03 5.290e+02 5.910e+02 5.650e+02 6.100e+02 4.100e+02
 3.730e+02 3.550e+02 7.970e+02 4.370e+02 4.510e+02 5.980e+02 4.350e+02
 5.160e+02 5.530e+02 5.230e+02 3.110e+02 5.370e+02 4.420e+02 3.710e+02
 3.380e+02 7.890e+02 7.170e+02 6.790e+02 5.200e+02 3.910e+02 6.320e+02

In [61]:
# Comprovar si hi ha dades duplicades al data set

duplicates = df.duplicated() # Retorna un boolean true (duplicat) o false (no duplicat)
count_duplicates = duplicates.value_counts()
print(count_duplicates)

# En aquest cas no hi havia

False    1936758
dtype: int64

## Exploració de les dades:

### Las variables que trobem al dataset són les següents:

- Year: 2008
- Month: 1-12
- DayofMonth: 1-31
- DayOfWeek: 1 (Dilluns) - 7 (Diumenge).
- DepTime: Hora de sortida real (local, hhmm).
- CRSDepTime: Hora de sortida programada (local, hhmm).
- ArrTime: Hora d'arribada real (local, hhmm).
- CRSArrTime: Hora d'arribada programada (local, hhmm).
- UniqueCarrier: Codi d'operador únic (Aerolínia). 
- FlightNum: Número de vol.
- TailNum: Número de cua de l'avió: és el registre de l'avió, un identificador únic de l'avió.
- ActualElapsedTime: Temps real de durada del vol en minuts. Resultat de sumar les variables: AirTime, TaxiIn i TaxiOut.
- CRSElapsedTime: Duració programada del vol. És el resultat de sumar ActualElapsedTime + ArrDelay (valors *negatius) + DepDelay.
- AirTime: Duració real del vol en minuts.
- ArrDelay: *Temps de retard a l’arribada, en minuts: En un vol es té en compte com "a temps" si el vol va operar en menys de 15 minuts després de l’hora programada que es mostra als Sistemes Computeritzats de Reserves (CRS) a les aerolínies. *Els valors negatius corresponen a una arribada abans de e temps.
- DepDelay: Retard a la sortida, en minuts.
- Origin: Origen IATA codi de l’aeroport.
- Dest: Desti IATA codi de l’aeroport.
- Distance: Distància en milles.
- Taxi-In: Taxi-In en minuts - És el temps que va des del moment de l’aterratge fins el moment del bloqueig.
- Taxi-Out: en minuts - És el temps que s’obté restant el temps des de que s’ extreuen les falques fins el temps d’enlairament real.
- Cancelled : Vol cancel·lat.
- CancellationCode: Motiu per la cancel·lació (A = operador, B = temps, C = NAS (Sistema Nacional de aviació, D = seguretat)
- Diverted: Desviat: 1 = yes, 0 = no
- CarrierDelay: en minuts. Retards associats a l’operador (aerolínies). Situacions que poden determinar un retard de l’operador són: Neteja de la aeronau, danys a l’aeronau, espera a l’arribada de passatgers o tripulació en connexió, equipatge, impacte amb aus, temps de càrrega, càtering, computadora, interrupció de l’equip de l’operador, legalitat de la tripulació (descans del pilot o assistent), danys per  mercaderies perilloses, inspecció d’enginyeria, aprovisionament de combustible, gestió de passatgers discapacitats, retard de la tripulació, servei de lavabo, manteniment, sobre vendes, servei d’aigua potable, trasllats o canvis en passatgers rebels, lentitud en l'embarcament o per seure, gestió de l’equipatge de mà, retards pel pes i l’equilibri.
- WeatherDelay: en minuts. Retards associats a les condicions climàtiques extremes o perilloses que es preveuen o es manifesten al moment de sortir, en ruta o al moment d’arribar.
- NASDelay: en minuts. El retard que està assignat al Sistema Nacional de l’Espai Aeri (NAS) pot incloure: condicions climàtiques no extremes, operacions aeroportuàries, volum de tràfic intens, control de tràfic aeri, etc.
- SecurityDelay: en minuts. El retards associats a la seguretat. Són causats per: l’evacuació d’una terminal o vestíbul, el reembarcament d’una aeronau degut a una violació de la  seguretat, equip de control inoperatiu i/o llargues cues a les àrees de control (més de 29 minuts).
- LateAircraftDelay: en minuts. Retard en l’arribada a l’aeroport com a conseqüència d’un retard en l’anterior aeroport. L’efecte dominó d’un retard anterior en els posteriors aeroports es coneix com a propagació del retard.

In [62]:
# Verificar si n'hi ha valors duplicats a la columna 'FlightNum'

duplicates_flight_num = df.duplicated(subset=['FlightNum'], keep=False)

# Verificar i mostrar el resultat conforme si n'hi ha valors duplicats

if duplicates_flight_num.any():
    print("Hi ha valors duplicats a 'FlightNum'.")
else:
    print("No hi ha valors duplicats a 'FlightNum'.")

Hi ha valors duplicats a 'FlightNum'.

In [63]:
# Comptar el valor duplicats a la columna 'FlightNum'

flight_num_counts = df['FlightNum'].value_counts()

print("Nombre de cops que apareix el vol 'FlightNum':")
flight_num_counts

Nombre de cops que apareix el vol 'FlightNum':

16      1586
50      1550
40      1507
15      1471
44      1447
        ...
7681       1
7032       1
6893       1
6914       1
5272       1
Name: FlightNum, Length: 7499, dtype: int64

In [64]:
# Identificar i explorar els valors duplicats a 'FlightNum'

duplicated_flight_nums = df[df.duplicated(subset=['FlightNum'], keep=False)]

# Ordenar les files duplicades per 'FlightNum'
sorted_duplicates = duplicated_flight_nums.sort_values(by='FlightNum')

# Mostrar les files duplicades a 'FlightNum', ordenades per la columna 'FlightNum'
print("Les files que contenen valors duplicats a 'FlightNum'i ordenades per 'FlightNum' són:")
sorted_duplicates.head(10)

Les files que contenen valors duplicats a 'FlightNum'i ordenades per 'FlightNum' són:

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,TailNum,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,DepDelay,Origin,Dest,Distance,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
166711,540842,2008,1,18,5,1156.0000,1150,1438.0000,1431,AS,1,N564AS,222.0000,221.0000,198.0000,7.0000,6.0000,SEA,ANC,1449,4.0000,20.0000,0,N,0,NaN,NaN,NaN,NaN,NaN
1709831,6355288,2008,11,11,2,921.0000,900,1217.0000,1230,AA,1,N338AA,356.0000,390.0000,330.0000,-13.0000,21.0000,JFK,LAX,2475,11.0000,15.0000,0,N,0,NaN,NaN,NaN,NaN,NaN
1709830,6355280,2008,11,3,1,916.0000,900,1236.0000,1230,AA,1,N339AA,380.0000,390.0000,336.0000,6.0000,16.0000,JFK,LAX,2475,8.0000,36.0000,0,N,0,NaN,NaN,NaN,NaN,NaN
891970,3019825,2008,6,10,2,715.0000,700,809.0000,800,WN,1,N284WN,54.0000,60.0000,42.0000,9.0000,15.0000,DAL,HOU,239,5.0000,7.0000,0,N,0,NaN,NaN,NaN,NaN,NaN
1672998,6171060,2008,11,9,7,841.0000,835,1248.0000,1301,US,1,N633AW,187.0000,206.0000,166.0000,-13.0000,6.0000,PHX,ORD,1440,6.0000,15.0000,0,N,0,NaN,NaN,NaN,NaN,NaN
474020,1487227,2008,3,21,5,915.0000,901,1741.0000,1741,DL,1,N3766,326.0000,340.0000,297.0000,0.0000,14.0000,SFO,JFK,2586,12.0000,17.0000,0,N,0,NaN,NaN,NaN,NaN,NaN
1349788,4550541,2008,8,27,3,1712.0000,1648,2003.0000,1945,DL,1,N3731T,171.0000,177.0000,131.0000,18.0000,24.0000,MCO,JFK,944,14.0000,26.0000,0,N,0,0.0000,0.0000,18.0000,0.0000,0.0000
1918773,6964910,2008,12,21,7,842.0000,825,1039.0000,945,B6,1,N656JB,117.0000,80.0000,61.0000,54.0000,17.0000,BUF,JFK,301,13.0000,43.0000,0,N,0,17.0000,0.0000,37.0000,0.0000,0.0000
1935036,7005129,2008,12,10,3,1730.0000,1702,2035.0000,2000,DL,1,N711ZX,185.0000,178.0000,141.0000,35.0000,28.0000,MCO,JFK,944,14.0000,30.0000,0,N,0,0.0000,0.0000,35.0000,0.0000,0.0000
1421624,4821775,2008,8,11,1,945.0000,935,1244.0000,1245,CO,1,N76064,479.0000,490.0000,455.0000,-1.0000,10.0000,IAH,HNL,3904,5.0000,19.0000,0,N,0,NaN,NaN,NaN,NaN,NaN

### Una vegada feta l'exploració, he press la decisió d'el·liminar les següents columnes:

- 'Unnamed: 0': No m'aporta cap valor aquesta numeració.
- Year': Tots els registres pertanyen a l'any 2008 i, per tant, en aquest moment podríem prescindir d'aquest valor.
- Podríem transformar les dades de "data" amb una sola columna, però ja que les tenim en diferents columnes, trobo molt interessant poder comprovar si existeixen patrons de comportament, pel que fa als retards, a determinat dia de la setmana, a principis o començaments de mes o a determinats mesos en relació amb els seus volums de vols per a cadascun d'aquests supòsits.
- FlightNum: Els valors no responen a cap patró, és a dir, els valors repetits no presenten cap lògica; no comparteixen ni origen ni destí, no són de cap companyia en concret, no tenen cap ordre pel que fa a l'hora de sortida, etc., per tant, entenc que és un valor aleatori i que no ofereix cap valor afegit.

- La resta de categories o columnes les he vist interessants depenent del tipus d'anàlisi que es vulgui dur a terme, ja que totes poden aportar un biaix a la informació.

In [139]:
columns_to_drop = ['Unnamed: 0','Year', 'FlightNum']
 
flights = df.drop(columns=columns_to_drop, axis=1)

flights.head(5)

,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,TailNum,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,DepDelay,Origin,Dest,Distance,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,1,3,4,2003.0000,1955,2211.0000,2225,WN,N712SW,128.0000,150.0000,116.0000,-14.0000,8.0000,IAD,TPA,810,4.0000,8.0000,0,N,0,NaN,NaN,NaN,NaN,NaN
1,1,3,4,754.0000,735,1002.0000,1000,WN,N772SW,128.0000,145.0000,113.0000,2.0000,19.0000,IAD,TPA,810,5.0000,10.0000,0,N,0,NaN,NaN,NaN,NaN,NaN
2,1,3,4,628.0000,620,804.0000,750,WN,N428WN,96.0000,90.0000,76.0000,14.0000,8.0000,IND,BWI,515,3.0000,17.0000,0,N,0,NaN,NaN,NaN,NaN,NaN
3,1,3,4,1829.0000,1755,1959.0000,1925,WN,N464WN,90.0000,90.0000,77.0000,34.0000,34.0000,IND,BWI,515,3.0000,10.0000,0,N,0,2.0000,0.0000,0.0000,0.0000,32.0000
4,1,3,4,1940.0000,1915,2121.0000,2110,WN,N726SW,101.0000,115.0000,87.0000,11.0000,25.0000,IND,JAX,688,4.0000,10.0000,0,N,0,NaN,NaN,NaN,NaN,NaN

### Transformació i neteja de dades

- Modifico les dades de Cancelled i Diverted per fer-les més comprensibles de cara un anàlisi.

In [66]:
# Renombrar els valors de les variables a 'Canceled' i 'Diverted'

flights['Cancelled']=flights['Cancelled'].replace([1,0],["Cancelled","Not Cancelled"])
flights['Diverted']=flights['Diverted'].replace([1,0],["Diverted","Not Diverted"])

- Veient les explicacions a kaggle sobre el dataset, els valors a les columnes 'CarrierDelay', 'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay' només s'omplen quan el retard a la variable arrDelay > 15 min. Entenent aquest fet, he pres la decisió de no esborrar les dades "NaN" per tal de no distorsionar els volums, en aquest cas positius, a la resta de variables. Si esborréssim els registres que no es consideren amb retard i després calculéssim el % de vols amb retard sobre un dia en concret el % es veuria alterat.

In [75]:
# Treure una mostra aleatòria de 200.000 registres amb llavor

sample_flights = flights.sample(n=200000, random_state=42)
sample_flights.head(10)

,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,TailNum,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,DepDelay,Origin,Dest,Distance,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
1782417,12,6,6,1805.0000,1755,2146.0000,2035,YV,N505MJ,281.0000,220.0000,177.0000,71.0000,10.0000,IAD,AUS,1297,5.0000,99.0000,Not Cancelled,N,Not Diverted,71.0000,0.0000,0.0000,0.0000,0.0000
512712,3,23,7,2120.0000,1200,2241.0000,1333,NW,N777NC,81.0000,93.0000,55.0000,548.0000,560.0000,ORD,MSP,334,7.0000,19.0000,Not Cancelled,N,Not Diverted,543.0000,0.0000,0.0000,0.0000,5.0000
447137,3,31,1,1731.0000,1710,1819.0000,1810,OO,N224SW,48.0000,60.0000,44.0000,9.0000,21.0000,SLC,PIH,150,3.0000,1.0000,Not Cancelled,N,Not Diverted,NaN,NaN,NaN,NaN,NaN
55082,1,6,7,1507.0000,1413,1601.0000,1509,OO,N708SK,54.0000,56.0000,32.0000,52.0000,54.0000,HDN,DEN,142,5.0000,17.0000,Not Cancelled,N,Not Diverted,0.0000,0.0000,0.0000,0.0000,52.0000
877634,5,22,4,637.0000,630,812.0000,750,CO,N16646,155.0000,140.0000,134.0000,22.0000,7.0000,JAX,IAH,817,5.0000,16.0000,Not Cancelled,N,Not Diverted,0.0000,0.0000,15.0000,7.0000,0.0000
1056704,6,12,4,2136.0000,2125,2300.0000,2230,AA,N3BHAA,204.0000,185.0000,174.0000,30.0000,11.0000,DFW,LAX,1235,13.0000,17.0000,Not Cancelled,N,Not Diverted,11.0000,0.0000,19.0000,0.0000,0.0000
198754,2,14,4,1807.0000,1800,1910.0000,1900,WN,N523SW,63.0000,60.0000,47.0000,10.0000,7.0000,DAL,HOU,239,7.0000,9.0000,Not Cancelled,N,Not Diverted,NaN,NaN,NaN,NaN,NaN
532837,3,23,7,1315.0000,1305,1937.0000,1915,AA,N5DYAA,262.0000,250.0000,216.0000,22.0000,10.0000,LAX,ORD,1745,24.0000,22.0000,Not Cancelled,N,Not Diverted,0.0000,0.0000,22.0000,0.0000,0.0000
1293928,8,31,7,1550.0000,1530,1704.0000,1652,XE,N10575,74.0000,82.0000,60.0000,12.0000,20.0000,LAX,SMF,373,3.0000,11.0000,Not Cancelled,N,Not Diverted,NaN,NaN,NaN,NaN,NaN
749884,5,22,4,1814.0000,1640,1923.0000,1755,WN,N468WN,69.0000,75.0000,52.0000,88.0000,94.0000,SJC,LAX,308,5.0000,12.0000,Not Cancelled,N,Not Diverted,15.0000,0.0000,0.0000,0.0000,73.0000

### Exercici 2

#### Fes un informe complet del dataset:

- Resumeix estadísticament el dataset i les columnes d’interès. Fes una anàlisi estadístic del que consideris rellevant.

In [80]:
custom_data = sample_flights [['Distance','AirTime', 'TaxiIn', 'TaxiOut', 'DepDelay', 'ArrDelay','ActualElapsedTime', 'CRSElapsedTime', 'CarrierDelay', 'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay']]

data_to_analyze = custom_data.describe()
data_to_analyze

,Distance,AirTime,TaxiIn,TaxiOut,DepDelay,ArrDelay,ActualElapsedTime,CRSElapsedTime,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
count,200000.0000,199127.0000,199267.0000,199956.0000,200000.0000,199127.0000,199127.0000,199974.0000,128970.0000,128970.0000,128970.0000,128970.0000,128970.0000
mean,764.9617,108.1971,6.8177,18.2171,43.3194,42.3715,133.2228,134.1849,19.1977,3.6911,15.0026,0.0912,25.4674
std,572.8567,68.4724,5.3428,14.4102,53.5814,57.0046,72.0014,71.1780,44.1262,20.8634,33.9139,2.0149,42.2759
min,11.0000,0.0000,0.0000,0.0000,6.0000,-57.0000,15.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000
25%,340.0000,58.0000,4.0000,10.0000,12.0000,9.0000,80.0000,82.0000,0.0000,0.0000,0.0000,0.0000,0.0000
50%,607.0000,90.0000,6.0000,14.0000,24.0000,25.0000,116.0000,116.0000,2.0000,0.0000,2.0000,0.0000,8.0000
75%,998.0000,137.0000,8.0000,21.0000,54.0000,56.0000,165.0000,165.0000,21.0000,0.0000,15.0000,0.0000,34.0000
max,4962.0000,644.0000,200.0000,342.0000,2467.0000,2453.0000,666.0000,660.0000,2436.0000,868.0000,1030.0000,280.0000,1012.0000

#### Resum anàlisi estadístic

- Podem observar que les dades de retard tant a la sortida com a l'arribada són força semblants:
- Que la mitjana és de 43,3 min de retard en el temps de sortida vs. 42,3 min en el temps d'arribada, que amb aquestes dades podríem dir que el temps no és recuperable en la major part dels casos i que, per tant, el problema resideix més a la sortida.
- Que el 75% dels vols surten amb un retard de 54 min.
- Que el mínim temps de retard en la sortida és de 6 min.
- Que també hi ha vols que arriben abans, 57 minuts abans seria el valor mínim registrat.
- Que es perd la major part del temps a la gestió o preparació per l'enlairament (TaxiOut), de 10 a 21 min. S'haurien de veure quines són les circumstàncies o raons.
- Que a major distància o temps de vol, major és el retard en l'arribada, teoria que refuta que el temps no és recuperable.
- Que el vols de llarga distància tenen més pes i com ha resultat tenim una mitjana alta.
- Que el major pes, pel que fa a les causes en el retard, recau pel conegut efecte dominó, seguit per problemes en l'operador i problemes associats al Sistema Nacional de l'Espai Aeri.

- Troba quantes dades faltants hi ha per columna.

In [79]:
flights.isnull().sum()

Month                     0
DayofMonth                0
DayOfWeek                 0
DepTime                   0
CRSDepTime                0
ArrTime                7110
CRSArrTime                0
UniqueCarrier             0
TailNum                   5
ActualElapsedTime      8387
CRSElapsedTime          198
AirTime                8387
ArrDelay               8387
DepDelay                  0
Origin                    0
Dest                      0
Distance                  0
TaxiIn                 7110
TaxiOut                 455
Cancelled                 0
CancellationCode          0
Diverted                  0
CarrierDelay         689270
WeatherDelay         689270
NASDelay             689270
SecurityDelay        689270
LateAircraftDelay    689270
dtype: int64

- A nivell general al data set té els següents valors null
 - Com he comentat abans, segons les explicacions a kaggle sobre el dataset, els valors a les columnes 'CarrierDelay', 'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay' només s'omplen quan el retard a la variable arrDelay > 15 min.
 - Els 8.387 valors null de 'ActualElapsedTime' correspondrien a vols cancelats.
 - I, per últim, s'hauria de veure perquè hi ha vols sense identificar l'avió (TailNum)
 - La resta de dades serien dependents.

- Crea columnes noves (velocitat mitjana del vol, si ha arribat tard o no...).

In [88]:
# Als EUA la velocitat s'expressa en milles per hora mph i com ens demana la velocitat mitjana tindrem en compte tot el temps transcorregut i no només el temps de vol.

flights['AvgSpeed'] = flights['Distance'] / (flights['ActualElapsedTime']/60)

# Per crear la variable booleana si ha arribat tard o no tindrem en compte el criteri utilitzat per Kaggle, només es considera retard aquells vols que arrDelay > 15 min.

flights['Delay'] = 'No'
flights.loc[flights['ArrDelay'] > 15, 'Delay'] = 'Yes'

flights.head(5)

,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,TailNum,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,DepDelay,Origin,Dest,Distance,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,AvgSpeed,Delay
0,1,3,4,2003.0000,1955,2211.0000,2225,WN,N712SW,128.0000,150.0000,116.0000,-14.0000,8.0000,IAD,TPA,810,4.0000,8.0000,Not Cancelled,N,Not Diverted,NaN,NaN,NaN,NaN,NaN,379.6875,No
1,1,3,4,754.0000,735,1002.0000,1000,WN,N772SW,128.0000,145.0000,113.0000,2.0000,19.0000,IAD,TPA,810,5.0000,10.0000,Not Cancelled,N,Not Diverted,NaN,NaN,NaN,NaN,NaN,379.6875,No
2,1,3,4,628.0000,620,804.0000,750,WN,N428WN,96.0000,90.0000,76.0000,14.0000,8.0000,IND,BWI,515,3.0000,17.0000,Not Cancelled,N,Not Diverted,NaN,NaN,NaN,NaN,NaN,321.8750,No
3,1,3,4,1829.0000,1755,1959.0000,1925,WN,N464WN,90.0000,90.0000,77.0000,34.0000,34.0000,IND,BWI,515,3.0000,10.0000,Not Cancelled,N,Not Diverted,2.0000,0.0000,0.0000,0.0000,32.0000,343.3333,Yes
4,1,3,4,1940.0000,1915,2121.0000,2110,WN,N726SW,101.0000,115.0000,87.0000,11.0000,25.0000,IND,JAX,688,4.0000,10.0000,Not Cancelled,N,Not Diverted,NaN,NaN,NaN,NaN,NaN,408.7129,No

- Fes una taula de les aerolínies amb més endarreriments acumulats.

In [108]:
print('Les aerolínies amb més endarreriment acumulat són:\n')

carrier_delay_total = flights.groupby('UniqueCarrier')['ArrDelay'].sum()
carrier_delay_total_sorted = carrier_delay_total.sort_values(ascending=False).reset_index()

carrier_delay_total_sorted

Les aerolínies amb més endarreriment acumulat són:

   UniqueCarrier      ArrDelay
0             WN 11319092.0000
1             AA  8889066.0000
2             UA  6733013.0000
3             MQ  6396704.0000
4             OO  5978936.0000
5             XE  5176042.0000
6             DL  4535644.0000
7             CO  4045932.0000
8             EV  3888131.0000
9             YV  3691461.0000
10            US  3571867.0000
11            NW  3462075.0000
12            FL  3100150.0000
13            B6  3025749.0000
14            OH  2675993.0000
15            9E  2420468.0000
16            AS  1406735.0000
17            F9   788549.0000
18            HA   255613.0000
19            AQ    15814.0000

- Quins són els vols més llargs? I els més endarrerits? Busca les rutes més llargues i les que acumulen més retards.

In [112]:
# Els vols més llargs, entenent per temps 

longest_flights = flights.sort_values(by='AirTime', ascending=False)

top_10_longest_flights = longest_flights[['UniqueCarrier', 'TailNum', 'AirTime', 'Distance', 'Origin', 'Dest']].head(10)

top_10_longest_flights

        UniqueCarrier TailNum   AirTime  Distance Origin Dest
1488690            HA  N586HA 1091.0000      2677    SEA  HNL
1367047            HA  N597HA  733.0000      2677    HNL  SEA
362529             CO  N67058  664.0000      4962    EWR  HNL
556381             CO  N66051  655.0000      4962    EWR  HNL
556385             CO  N59053  654.0000      4962    EWR  HNL
556379             CO  N66051  654.0000      4962    EWR  HNL
556377             CO  N76062  652.0000      4962    EWR  HNL
556386             CO  N78060  651.0000      4962    EWR  HNL
362852             CO  N76055  649.0000      4962    EWR  HNL
363750             CO  N67052  648.0000      4962    EWR  HNL

In [114]:
# Els més endarrerits

most_delayed_flights = flights.sort_values(by='ArrDelay', ascending=False)

top_10_most_delayed_flights = most_delayed_flights[['UniqueCarrier', 'TailNum', 'ArrDelay', 'Distance', 'Origin', 'Dest']].head(10)

top_10_most_delayed_flights

        UniqueCarrier TailNum  ArrDelay  Distance Origin Dest
322516             NW  N817NW 2461.0000      3972    HNL  MSP
686014             NW  N3324L 2453.0000       930    CLT  MSP
839306             NW  N333NW 1951.0000      1085    RSW  DTW
1009553            MQ  N512AE 1707.0000       304    LIT  DFW
1881639            NW  N366NW 1655.0000      1124    BOS  MSP
1497823            NW  N322US 1583.0000       282    OMA  MSP
685437             NW  N8986E 1542.0000       449    MOT  MSP
163379             AA  N622AA 1525.0000      1811    EGE  MIA
1214839            NW  N596NW 1510.0000      1399    SEA  MSP
521096             NW  N786NC 1490.0000       200    BNA  MEM

In [127]:
# Les rutes més llargues

flights['Route'] = flights[['Origin', 'Dest']].min(axis=1) + '-' + flights[['Origin', 'Dest']].max(axis=1)

unique_routes = flights[['Route', 'Distance']].drop_duplicates()

top_longest_routes = unique_routes.sort_values(by='Distance', ascending=False)

top_longest_routes.head(5)

          Route  Distance
173177  EWR-HNL      4962
96292   ATL-HNL      4502
66587   HNL-ORD      4243
66613   KOA-ORD      4213
66624   OGG-ORD      4184

- Els vols més llargs tant d'anada com de tornada són entre:
    - Honolulu i Newark (New Jersey)
    - Atlanta i Honolulu
    - Honolulu i O'Hare (Chicago)
    - Kona (Hawái) i O'Hare (Chicago)
    - Kahului (Hawái) i O'Hare (Chicago)

In [131]:
# Les rutes que acumulen més retards.

unique_routes = flights[['Route', 'ArrDelay']].drop_duplicates()

top_longest_routes = unique_routes.sort_values(by='ArrDelay', ascending=False)

top_longest_routes.head(5)

           Route  ArrDelay
322516   HNL-MSP 2461.0000
686014   CLT-MSP 2453.0000
839306   DTW-RSW 1951.0000
1009553  DFW-LIT 1707.0000
1881639  BOS-MSP 1655.0000

- Els vols que acumulen més retrads tant d'anada com de tornada són entre:
    - Honolulu i Minneapolis
    - Charlotte (Carolina del Norte) i Minneapolis
    - Detroit i Florida
    - Dallas-Fort Worth i Arkansas
    - Bostón i Minneapolis

- Aporta allò que consideris rellevant.

In [137]:
print('Retards acumulats segons el dia de la setmana:\n')
      
delay_per_day = flights.groupby('DayOfWeek')['ArrDelay'].sum()

delay_per_weekday = delay_per_day.sort_values(ascending=False).reset_index()

delay_per_weekday

Retards acumulats segons el dia de la setmana:

   DayOfWeek      ArrDelay
0          5 14004162.0000
1          7 12736081.0000
2          1 12094665.0000
3          4 11842749.0000
4          2 11371513.0000
5          3 10574516.0000
6          6  8753348.0000

#### Com era d'esperar els dies de la setmana on es produeixen més retards són divendres, diumenge i dilluns, dies que coincideixen amb més tràfic per les sortides i arribades tant per cap de setmana com primer dia de la setmana per feina.

### Exercici 3

- Exporta el dataset net i amb les noves columnes a Excel.

In [ ]:
sample_flights.to_excel('/Users/sergi/Downloads/flights_airlines_delay.xlsx', index=False)